### ISSUE TITLE
Old leasing transactions not appearing on leasing tab.

### ISSUE THREAD

**Issue by sejudge** [wavesplatform/WavesGUI#244]
The older, but still active, leasing transactions are vanishing from the **leasing** page of the lite client.  This prevents the lease from being cancelled.  

The disappearance of these active leasing transactions appears to be correlated to their roll-off of the recent transactions list on the **history** page.

Re: lite client 0.4.21a

**Comment by xenohunter** [comment]
Hello and thank you for reporting this. Yes, we know about the issue, it happens due to the lack of an appropriate Node API method. It will be added soon, and that will be fixed.

**Comment by sejudge** [comment]
Nice job!

**Comment by xenohunter** [comment]
Thanks! Though it will be fully fixed only with the changes in the Node API. I hope that happens soon.

**Comment by sejudge** [comment]
I see what you'tr saying.  Transactions have run these old leases off my account once more.  I too hope the API is fixed soon.

**Comment by grefa** [comment]
Таже проблемма.. и как теперь отменить лизинговые транзакции??

**Comment by xenohunter** [comment]
Right now there are two options:
* to parse all the blocks and to find your lease transaction, or
* to restore the transaction ID if you stored it before

and then cancel it using Waves Node or a client-side API library (for example, [waves-api](https://github.com/xenohunter/waves-api) or [PyWaves](https://github.com/PyWaves)).

The new API is coming quite soon, and in the new Client there will be a full list of all transactions.

**Comment by kivancekici** [comment]
Hi, xenohunter you mentioned :"The new API is coming quite soon, and in the new Client there will be a full list of all transactions.",

The bug is present with the newly released beta client and not all transactions are listed. The priority of this bug should be elevated to the highest, it is harming Waves because users money locked in leasing and some of the pools are not paying anything at all.

**Comment by xenohunter** [comment]
Hello! I share your concern entirely. The new API was delayed due to hard work on Waves-NG. We will add that functionality really soon. I should mention @alexkof here, I guess.

**Comment by prashin123** [comment]
Hey, pleases fix this issue.
I have some waves leased to fountain perpetua but i cannot find them leasing page of the lite client. Due to this, I cannot cancel them.
Morever, I saw on twitter that fountain perpetua is closing as a generating node.

I want to cancel my leases, but i cannot.
Please help.

**Comment by xenohunter** [comment]
Hello! Could you please reach out to someone from our backend team (@alexkof or @koloale for instance)? I guess they could help with that single transaction. We're still working on the API method.

**Comment by kraksaa** [comment]
This problem applies to everyone. Do something!

**Comment by AndrewDowning** [comment]
Hey, so nearly a year later, and real users of Waves still have leased Waves that are inaccessible because of this bug. What's the story?

**Comment by xenohunter** [comment]
Hello everybody! In fact, the issue was fixed quite a time ago. In the beta Waves Client all the leasing transactions are visible: https://beta.wavesplatform.com/wallet/leasing.
