### ISSUE TITLE
Need help to register on the forum

### ISSUE THREAD

**Issue by salisbury-espinosa** [wavesplatform/WavesGUI#255]
The link to the forum is taken from `WavesExplorerLite`

I was unable to register on the forum via facebook:

![bug](https://user-images.githubusercontent.com/18151481/26991656-f3a8d300-4d63-11e7-86ec-84012893c608.png)

And via twitter:

https://wavestalk.org/index.php?action=twitter;sa=register;submit

![bug_2](https://user-images.githubusercontent.com/18151481/26992061-a1aae29e-4d65-11e7-9fb9-15de938b8856.png)

=>

![screen_from_forum](https://user-images.githubusercontent.com/18151481/26992096-bbb296b4-4d65-11e7-9262-ce29e48b2eb1.png)

PS
I wanted to ask on the forum - http://lapti.co/  Is it a project associated with the platform waves?  
Two of your team (https://github.com/orgs/wavesplatform/people) are there as a CEO and CTO

**Comment by salisbury-espinosa** [comment]
I got the answers from https://wavesplatform.slack.com

**Comment by xenohunter** [comment]
Hi @salisbury-espinosa! `WavesExplorerLite` is not the app we work on. Concerning Lapti, our project is independent but it supports Waves as a currency and a platform for token distribution. If you have questions on it, please contact me [on Facebook](https://www.facebook.com/xenohunter) instead of answering here.
